### ISSUE TITLE
Structure of a ***vp***.h5 file

### ISSUE THREAD

**Issue by plieper** [enram/data-repository#17]
H5File 'czska_vp_20170110001400.h5' (mode 'r+')
+ dataset1
  + data1
    + what
      A gain
      A nodata
      A offset
      A quantity
      A undetect 
    D data  
  + data10
  + data11
  + data12
  + data13
  + data14
  + data15
  + data2
  + data3
  + data4
  + data5
  + data6
  + data7
  + data8
  + data9 
+ how
  A beamwidth
  A clutterMap
  A comment
  A maxazim
  A maxrange
  A minazim
  A minrange
  A rcs_bird
  A sd_vvp_thresh
  A task
  A task_args
  A task_version
  A wavelength 
+ what
  A date
  A object
  A source
  A time
  A version 
+ where
  A height
  A interval
  A lat
  A levels
  A lon
  A maxheight
  A minheight 
A Conventions

**Comment by adokter** [comment]
See also https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification

**Comment by peterdesmet** [comment]
We decided not to develop a data model and database for bird profile data, since there was no strong use case to do so, but rather extend the bioRad package to download and load bird profiles directly from the data repository on S3. Closing this issue.
