### ISSUE TITLE
Deploy file transfer script on AWS and run daily

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#19]
The [Baltrad to S3 script](https://github.com/enram/infrastructure/issues/18) should be deployed somewhere (Micro instance, Lambda) and run daily.

**Comment by stijnvanhoey** [comment]
Currently running to check the robustness of the setup, ec2 microinstance (ubuntu) with a daily cron job. As the algorithm output from Baltrad is still under revision, the bulk update of the data will be required. Closing this issue here, documentation of file transfer is next on (issue #24).
