### ISSUE TITLE
Document file_transfer

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#24]
Has already started at https://github.com/enram/infrastructure/tree/master/file_transfer, but that was written without an implementation.

**Comment by peterdesmet** [comment]
Also, that README includes the directory structure, which is now part of the [main README](https://github.com/enram/data-repository/blob/master/README.md#file-transfer-to-the-data-repository). I think the [README in file_transfer](https://github.com/enram/data-repository/blob/master/file_transfer/README.md) can be reduced to describe the functionality that is actually provided. @stijnvanhoey, can you do this?

**Comment by stijnvanhoey** [comment]
Documentation is split up, with the README in file_transfer focusing on the functionalities of the datamover. Closing here.
