### ISSUE TITLE
Document filename conventions

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#27]
Best to do this on the website itself or at least link to documentation from there.

**Comment by peterdesmet** [comment]
@jshamoun, I have described the directory structure and naming conventions in the README: https://github.com/enram/data-repository#browsing-the-data Is it understandable?

If so, I will link to this file from the repository itself.

**Comment by jshamoun** [comment]
Very clear to me. I like the combination of the visual tree and the text. Is the three letter code for the radar the same convention used in OPERA (or somewhere else) if so, worth mentioning. I think it is the opera convection and more info about each radar can be found on their website: http://eumetnet.eu/wp-content/themes/aeron-child/observations-programme/current-activities/opera/database/OPERA_Database/index.html
I am guessing that it is the last 3 letters of the ODIM code

**Comment by plieper** [comment]
Confirmation: yes, the naming of country and radar is according to ODIM.

**Comment by peterdesmet** [comment]
README just updated: https://github.com/enram/data-repository#browsing-the-data

**Comment by peterdesmet** [comment]
[On the website](http://enram.github.io/data-repository/) I have added:

* the same introduction as the README
* A link to the documentation
* A footer similar to the bird-migration-flow-viz.

Closing this issue.
