### ISSUE TITLE
Indicate a license for the data

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#31]
I strongly suggest to use [Creative Commons Zero](https://creativecommons.org/publicdomain/zero/1.0/), which we have also chosen for our [case study](https://github.com/enram/case-study).

Next to the license, it would be good to indicate how people can cite the ENRAM data repository for bird profiles: we could either invent something, deposit to Zenodo (not as straightforward as putting the code on Zenodo) or wait until we have written a data paper.

**Comment by niconoe** [comment]
@peterdesmet: this is already done at the top of the [data repository](https://enram.github.io/data-repository/), no? Should we close this issue?

**Comment by adokter** [comment]
Indirectly related but FYI: the ENRAM license for dealing with polar volume data with OPERA has been updated this week, valid now until Dec 31 2023.

**Comment by peterdesmet** [comment]
@niconoe indeed, I'll close this one.
