### ISSUE TITLE
update disclaimer on ENRAM portal that people need to cite OPERA in publications

### ISSUE THREAD

**Issue by adokter** [enram/data-repository#32]
On http://enram.github.io/data-repository/ we should make more clear that people need to acknowledge OPERA when using profile data, something like this:

We acknowledge EUMETNET/OPERA for providing access to European radar data. Access to single site radar data was made possible through a license agreement for research use of OPERA data between EUMETNET/OPERA members and ENRAM.

**Comment by adokter** [comment]
We should primarily mention OPERA, referring to Baltrad is more secondary, although it's good to mention that the actual algorithm runs there. But it's primarily OPERA we need to acknowledge, not BALTRAD

**Comment by peterdesmet** [comment]
There are two things:

* We should acknowledge EUMETNET/OPERA in the intro of the data repository (and README). I can do this, but please give me the correct phrasing to reference Eumetnet/OPERA in one swoop. Is it "Eumetnet OPERA"?
* We should provide a recommended citation for people using the bird profile data. Until we have a data paper, this citation should at least include the URL. We could list ENRAM, Eumetnet and OPERA as "authors". My suggestion:

> ENRAM & Eumetnet OPERA: ENRAM data repository for bird profiles. Dataset. Accessed via http://enram.github.io/data-repository/ on yyyy-mm-dd

**Comment by adokter** [comment]
The official name of the EUMETNET program is "European Operational Program for Exchange of Weather Radar Information (OPERA)"

**Comment by adokter** [comment]
As long as the methods paper related to the bioRad package isn't ready (which contains the most recent version of the vol2bird algorithm), I think we should cite 

Bird migration flight altitudes studied by a network of operational weather radars
Adriaan M. Dokter, Felix Liechti, Herbert Stark, Laurent Delobbe, Pierre Tabary, Iwan Holleman
J. R. Soc. Interface 2011 8 30-43; DOI: 10.1098/rsif.2010.0116.

Currently that's the only publication that explains how the vertical profiles of bird are generated.

We try to refer to them as a VPB (vertical profile of birds), which may be terminology you also want to stick to at the repository (i.e. a single hdf5 file contains one VPB)

**Comment by adokter** [comment]
We try to refer to a vertical profiles of birds as a VPB, which may be terminology you also want to stick to at the repository (i.e. a single hdf5 file contains one VPB). In meteorology there is already something called a VPR, a vertical profile of reflectivity, so trying to adjust to existing jargon.

**Comment by adokter** [comment]
This is a good reference that explains what OPERA is:
http://journals.ametsoc.org/doi/pdf/10.1175/BAMS-D-12-00216.1

**Comment by adokter** [comment]
@peterdesmet Just a reminder: this one really needs to be updated now that the archive will contain data that people may use. Please do not mention Baltrad but OPERA (EUMETNET program  "European Operational Program for Exchange of Weather Radar Information (OPERA)". The access page should also clearly state that all publications from this work should cite OPERA

**Comment by peterdesmet** [comment]
Started a pull request: #44. Let's continue conversation there, because there is a lot to decide. 😄

**Comment by peterdesmet** [comment]
Fixed in #44. Closing here.
