### ISSUE TITLE
Cannot open h5 file with bioRad

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#37]
See https://github.com/enram/vp-processing/issues/4: some files in repository seem to be corrupted.

**Comment by adokter** [comment]
Not sure this is relevant here, but note [bioRad](https://github.com/adokter/bioRad)'s `is.vpfile` function is available for checking file integrity

**Comment by peterdesmet** [comment]
Thanks @adokter that well help to check!

**Comment by stijnvanhoey** [comment]
fixed

**Comment by peterdesmet** [comment]
@stijnvanhoey do we have a whole bunch of old files that are corrupted now or can we reprocess those?

**Comment by stijnvanhoey** [comment]
Currently working on excluding the corrupted data. 

Reprocessing is possible from the server of Amsterdam, if @plieper provides access to the server.
