### ISSUE TITLE
Figure out how to flyway vp data

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#39]
I received the vp data for the flyway analysis from @CeciliaNilsson709 on a USB stick.

@stijnvanhoey, how easily can I run the `file_transfer` functionality over this to upload these data to the repository?

**Comment by stijnvanhoey** [comment]
If you have the proper rights to upload to the S3 bucket (`aws_access_key_id` and `aws_secret_access_key` in an aws-credentials file):

```
[lw-enram]
aws_access_key_id=xxxxxxxxxxxxxxxxxxxxx
aws_secret_access_key=xxxxxxxxxxxxxxxxxx
```

You can upload the code yourself from your local computer:
```python
ltos = dm.LocalToS3(filepath="../example_data/", bucket_name="lw-enram", profile_name="lw-enram")
ltos.transfer(name_match="_vp_", overwrite=False, limit=5, verbose=True) # low limit for initial test
```

**Comment by peterdesmet** [comment]
Thanks for the help! Upload is now running for a single radar. It's super slow though. 😴

**Comment by stijnvanhoey** [comment]
Uploading not optimized for speed as the daily load is rather small, so no design of the code for hugh data uploads...
