### ISSUE TITLE
Polish data has .hdf extension

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#41]
@CeciliaNilsson709 @plieper I noticed the data from the Polish radars have a `.hdf` extension, rather than the expected `.h5`:

> plbrz_vp_2016100100042700.hdf

As a result, the `file_transfer` does not recognize these files and they cannot be uploaded to the data repository... at least, that's what I think happens: I get an error. 🤷‍♂️

Can those files be changed to `.h5`?

**Comment by adokter** [comment]
@peterdesmet yes you can change to .h5, the difference is because Anna Gorska processed these data herself, and chose her own filenames.

**Comment by peterdesmet** [comment]
So, can I just replace the file extension or do I need to do something fancier?

**Comment by adokter** [comment]
Yes just change hdf into h5

**Comment by peterdesmet** [comment]
Great! It's done, and the files are still readable by bioRad. 👌

**Comment by peterdesmet** [comment]
Note to self: I used [Automator](http://zentraal.com/docs/recursive-file-rename-on-os-x-using-automator), rather than figuring out a bash script.
