### ISSUE TITLE
Shortname for vertical bird profiles: vp or vpb

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#43]
Just rediscovered @adokter [comment](https://github.com/enram/data-repository/issues/32#issuecomment-284846626):

> We try to refer to a vertical profiles of birds as a VPB, which may be terminology you also want to stick to at the repository (i.e. a single hdf5 file contains one VPB). In meteorology there is already something called a VPR, a vertical profile of reflectivity, so trying to adjust to existing jargon.

Does this still hold true? If so, the terminology `vertical profiles of birds` (rather than `vertical bird profiles`) and `VPB` (not `vp`) needs to be updated in a bunch of tools:

* Repository: already uses `vertical profiles of birds`, no acronyms
* bioRad: has functions `bioRad::readvp()`
* vp-processing: uses `vp` throughout
* Data files: contain `_vp_` which is unlikely to change

I'd like to have this consistent, but we need to be sure, so we only have to change all this once (and know where we can't).

**Comment by adokter** [comment]
I do try to promote the acronym VPB when talking about profiles of bird speed and direction. However, the vol2bird/bioRad vertical profiles also contain profile information on rain (and in the future, potentially insects). Therefore I chose for the more generic `vp`, which is also the OPERA/ODIM acronym for a vertical profile.

In short: stick with `vp`

**Comment by peterdesmet** [comment]
Ok, and any preference on "vertical bird profiles" vs "vertical profiles of birds"?
