### ISSUE TITLE
Upload flyway data batch 2

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#45]
The second batch of flyway data includes 8 radars:

```
bgvar
bejab
bezav
bewid
plrze
ptfar
ptliz
ptprt
```

Which have the expected date range of 2016-09-19/2016-10-09 (except pt). The `bg` and `be` data are every 5 minutes, the `pl` and `pt` data every 10 minutes. I've added the coverage stats to the Spreadsheet. @CeciliaNilsson709 can you have a look?

Important before I upload:

1. For the pt radars, the date range is 2016-08-01/2016-11-30 (much larger). Do I (cf. the German) data (which had 10 extra days) upload all that data, or just the flyway range (2016-09-19/2016-10-09).
2. For the Belgian data, minute 55 is missing for every hour. Is that expected?

**Comment by plieper** [comment]
Hi Peter,

1. I don't think there is no reason not to upload all the data? :-)
2. I had a look in the Belgian raw data, minute 55 seems to be missing very often indeed, I don't know why. Belgians! ;-)

**Comment by CeciliaNilsson709** [comment]
1. Yeah, you can just as well upload it all.

2. Belgians 🤷‍♀️ indeed.

**Comment by peterdesmet** [comment]
1. OK
2. Hey, you can't just throw your hands in the air and blame 👉 Belgians. 😂 But ok, I'll upload the data as it is.

**Comment by peterdesmet** [comment]
All data from batch 2 are now uploaded (warts and all)! 👏  Closing issue.
