### ISSUE TITLE
Offer combined data products

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#5]
### Do we really need to build this? And if so, how do we keep it simple?

The most simple would be not to offer this: users just have to download the separate radar/day files and combine those themselves.
### If we do offer this
- [ ] Do we build them on request - i.e. when the user wants to download them through the app - in effect creating a "download" OR do we pre-build them, e.g. combining the data for all radars in a monthly/yearly csv/sql lite? The advantage of the "downloads" is that they answer a custom need and can be periodically removed, freeing up disk space.
- [ ] In what format do we offer these? For the bird tracking data we offer SQLite and CSV. The SQLite is a very simple format, but offers indeces and allows the data to be queried using SQL.

**Comment by adokter** [comment]
For researchers the ability to query a database by SQL is very helpful, and is the preferred way of making data available from my perspective

**Comment by peterdesmet** [comment]
@adokter, what interface would you like to the database?

- We suggest an example R script to make a connection to the database and retrieve data
- Maybe a GUI interface, such as https://www.pgadmin.org/

**Comment by adokter** [comment]
* simple R script would be good for most users
* ability to use pgadmin to browse the contents of the db also handy
* add ODBC support if people want to use other programs?

**Comment by peterdesmet** [comment]
Great, then my new schema is correct: https://github.com/enram/infrastructure/blob/master/schema.svg
R and pgAdmin would most likely go through ODBC, so that would be covered too then.

**Comment by peterdesmet** [comment]
We decided not to develop a data model and database for bird profile data, since there was no strong use case to do so, but rather extend the bioRad package to download and load bird profiles directly from the data repository on S3. Closing this issue.

If there is a strong use case for it, we can attempt to do this in another STSM.
