### ISSUE TITLE
Organize files under new folder structure (similar to US)

### ISSUE THREAD

**Issue by peterdesmet** [enram/data-repository#54]
Suggestion by @adokter to change directory structure to date first, radar next:

Currently:

```
be/jab/2018/                12 monthly bejab201809.zip
be/jab/2018/09/28/10/       12 vp files
```

Proposal:

```
vp/2018/03/21/bejab/        12 x 24 = 288 vp files
vpts/2018/03/bejab/         1 vpts txt file
```

Differences:

- Similar to US structure
- Year first: quicker overview of temporal scope
- Country + radar together, to have quicker list of all available radars for that month
- No hour directories
- Don't mix file types: `vp` vs `vpts`. Also needed because `vp` data will be organized by day ( files/day) while `vpts` data will be shown monthly

@CeciliaNilsson709 @baptischmi @jshamoun or any other user of the repository... comments? If adopted we'll update the bioRad functionality to access the files.

**Comment by baptischmi** [comment]
Changes are fine to me. And i'm looking forwards to extra functionalities to quickly visualise file availability (or even VPTS) time-wise or spatial-wise.

**Comment by peterdesmet** [comment]
@baptischmi, we'll be supporting that by having vpts txt files per month (updated daily)

**Comment by jshamoun** [comment]
Thoughts on this:
Benefit is it would be similar to US
Would be easier to collect data for a single date
Would be harder to collect a time series for a single radar
So which is better depends on the research question. Having the vpts would help a lot. Having a database would be even better ☺

**Comment by peterdesmet** [comment]
The US folder structure has the disadvantage that radars don't have their directory. A new folder structure is suggested in #65. Closing this one.
